# Generated by Django 5.2.1 on 2025-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('learner', 'Learner'), ('teacher', 'Teacher'), (None, 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('learner', 'Learner'), ('teacher', 'Teacher')], default='user', max_length=20),
        ),
    ]
