# Generated by Django 5.2.1 on 2025-05-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_extractedtext_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='material',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='extracted_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='materials.extractedtext'),
            preserve_default=False,
        ),
    ]
